# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk16

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту shadar90ru@gmail.com если сборка упала
notifications:
  email:
    recipients:
      - shadar90ru@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
env:
  global:
    - CODECOV_TOKEN="5cb2d221-8400-4be2-a057-db13ea2b7c25"